# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Release

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build all packages
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      security-events: write  
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: | 
        mkdir out
        dotnet publish -c Release -r win-x64 --self-contained false -p:PublishReadyToRun=true
        zip -9 out/win-x64 bin/Release/net7.0/win-x64/publish/*
        rm -rf bin/
        dotnet publish -c Release -r win-x86 --self-contained false -p:PublishReadyToRun=true
        zip -9 out/win-x86 bin/Release/net7.0/win-x86/publish/*
        rm -rf bin/
        dotnet publish -c Release -r linux-x64 --self-contained false -p:PublishReadyToRun=true
        zip -9 out/linux-x64 bin/Release/net7.0/linux-x64/publish/*
        rm -rf bin/
        dotnet publish -c Release -r linux-arm --self-contained false -p:PublishReadyToRun=true
        zip -9 out/linux-arm bin/Release/net7.0/linux-arm/publish/*
        rm -rf bin/
        dotnet publish -c Release -r linux-arm64 --self-contained false -p:PublishReadyToRun=true
        zip -9 out/linux-arm64 bin/Release/net7.0/linux-arm64/publish/*
        rm -rf bin/
    - run: ls -la out/
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          out/win-x64.zip 
          out/win-x86.zip 
          out/linux-x64.zip 
          out/linux-arm.zip 
          out/linux-arm64.zip 
    - uses: actions/upload-artifact@v3
      with:
        name: build
        path: |
          out/win-x64.zip 
          out/win-x86.zip 
          out/linux-x64.zip 
          out/linux-arm.zip 
          out/linux-arm64.zip 