# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Release

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build all packages
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      security-events: write  
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: | 
        mkdir release
        dotnet publish -c Release -r win-x64 --self-contained false -p:PublishReadyToRun=true
        dotnet publish -c Release -r win-x86 --self-contained false -p:PublishReadyToRun=true
        dotnet publish -c Release -r linux-x64 --self-contained false -p:PublishReadyToRun=true
        dotnet publish -c Release -r linux-arm --self-contained false -p:PublishReadyToRun=true
        dotnet publish -c Release -r linux-arm64 --self-contained false -p:PublishReadyToRun=true
        cp bin/Release/net7.0/win-x64/publish/* release/
        tar -czf win-x64.tar.gz release
        rm -rf release
        cp bin/Release/net7.0/win-x86/publish/* release/
        tar -czf win-x86.tar.gz release
        rm -rf release
        cp bin/Release/net7.0/linux-x64/publish/* release/
        tar -czf linux-x64.tar.gz release
        rm -rf release
        cp bin/Release/net7.0/linux-arm/publish/* release/
        tar -czf linux-arm.tar.gz release
        rm -rf release
        cp bin/Release/net7.0/linux-arm64/publish/* release/
        tar -czf linux-arm64.tar.gz release
        rm -rf release
    - run: ls -la 
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          win-x64.tar.gz
          win-x86.tar.gz
          linux-x64.tar.gz
          linux-arm.tar.gz
          linux-arm64.tar.gz
    - uses: actions/upload-artifact@v3
      with:
        name: build
        path: |
          win-x64.tar.gz
          win-x86.tar.gz
          linux-x64.tar.gz
          linux-arm.tar.gz
          linux-arm64.tar.gz