# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Release

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build all packages
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      security-events: write  
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: | 
        mkdir out
        dotnet publish -c Release -r win-x64 --self-contained false -p:PublishReadyToRun=true
        dotnet publish -c Release -r win-x86 --self-contained false -p:PublishReadyToRun=true
        dotnet publish -c Release -r linux-x64 --self-contained false -p:PublishReadyToRun=true
        dotnet publish -c Release -r linux-arm --self-contained false -p:PublishReadyToRun=true
        dotnet publish -c Release -r linux-arm64 --self-contained false -p:PublishReadyToRun=true
        cd bin/Release/net7.0/win-x64/publish/
        tar -czf win-x64.tar.gz .
        cd ../../../../../bin/Release/net7.0/win-x86/publish
        tar -czf win-x86.tar.gz 
        cd ../../../../../bin/Release/net7.0/linux-x64/publish
        tar -czf linux-x64.tar.gz bin/Release/net7.0/linux-x64/publish
        cd ../../../../../bin/Release/net7.0/linux-arm/publish
        tar -czf linux-arm.tar.gz bin/Release/net7.0/linux-arm/publish
        cd ../../../../../bin/Release/net7.0/linux-arm64/publish
        tar -czf linux-arm64.tar.gz bin/Release/net7.0/linux-arm64/publish
    - run: ls -la bin/Release/net7.0/
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          bin/Release/net7.0/win-x64/publish/win-x64.tar.gz
          bin/Release/net7.0/win-x86/publish/win-x86.tar.gz
          bin/Release/net7.0/linux-x64/publish/linux-x64.tar.gz
          bin/Release/net7.0/linux-arm/publish/linux-arm.tar.gz
          bin/Release/net7.0/linux-arm64/publish/linux-arm64.tar.gz
    - uses: actions/upload-artifact@v3
      with:
        name: build
        path: |
          bin/Release/net7.0/win-x64/publish/win-x64.tar.gz
          bin/Release/net7.0/win-x86/publish/win-x86.tar.gz
          bin/Release/net7.0/linux-x64/publish/linux-x64.tar.gz
          bin/Release/net7.0/linux-arm/publish/linux-arm.tar.gz
          bin/Release/net7.0/linux-arm64/publish/linux-arm64.tar.gz